"""The base characters' animation lists in Sonic 1 / Sonic 2 (from their .ani files in Origins: extracted/<game>/Data/
Animations/<Base>.ani), so `noswap check` works without the extracted game data. "all": every name, in order; "filled": the
ones the base character has frames for (an extra that leaves one of these empty shows nothing there).
Regenerate by reading the .ani files with tools/sheet2ani.read_ani if Origins ever changes them."""

TEMPLATES = {('Sonic1', 'knuckles'): {'all': ['Stopped', 'Waiting', 'Bored!', 'Looking Up', 'Looking Down', 'Walking', 'Running',
                                  'Skidding', 'Super Peel Out', 'Spin Dash', 'Jumping', 'Bouncing', 'Hurt', 'Dying',
                                  'Drowning', 'Fan Rotate', 'Breathing', 'Pushing', 'Flailing 1', 'Flailing 2',
                                  'Sliding', 'Hanging', 'Dropping', 'Clinging On', 'Flying', 'Flying Tired',
                                  'Swimming', 'Swimming Tired', 'Gliding', 'Gliding Drop', 'Gliding Stop', 'Climbing',
                                  'Ledge Pull Up', 'Corkscrew H', 'Corkscrew V', 'Water Slide', 'Continue',
                                  'Continue Up', 'Super Transform'],
                          'filled': ['Stopped', 'Waiting', 'Bored!', 'Looking Up', 'Looking Down', 'Walking',
                                     'Running', 'Skidding', 'Spin Dash', 'Jumping', 'Bouncing', 'Hurt', 'Dying',
                                     'Drowning', 'Fan Rotate', 'Breathing', 'Pushing', 'Flailing 1', 'Flailing 2',
                                     'Hanging', 'Dropping', 'Clinging On', 'Gliding', 'Gliding Drop', 'Gliding Stop',
                                     'Climbing', 'Ledge Pull Up', 'Corkscrew H', 'Water Slide', 'Continue',
                                     'Continue Up', 'Super Transform']},
 ('Sonic1', 'sonic'): {'all': ['Stopped', 'Waiting', 'Bored!', 'Looking Up', 'Looking Down', 'Walking', 'Running',
                               'Skidding', 'Super Peel Out', 'Spin Dash', 'Jumping', 'Bouncing', 'Hurt', 'Dying',
                               'Drowning', 'Fan Rotate', 'Breathing', 'Pushing', 'Flailing 1', 'Flailing 2',
                               'Sliding', 'Hanging', 'Dropping', 'Clinging On', 'Flying', 'Flying Tired', 'Swimming',
                               'Swimming Tired', 'Launcher', 'Gliding Drop', 'Gliding Stop', 'Climbing',
                               'Ledge Pull Up', 'Corkscrew H', 'Corkscrew V', 'Water Slide', 'Continue',
                               'Continue Up', 'Super Transform'],
                       'filled': ['Stopped', 'Waiting', 'Looking Up', 'Looking Down', 'Walking', 'Running',
                                  'Skidding', 'Super Peel Out', 'Spin Dash', 'Jumping', 'Bouncing', 'Hurt', 'Dying',
                                  'Drowning', 'Fan Rotate', 'Breathing', 'Pushing', 'Flailing 1', 'Flailing 2',
                                  'Hanging', 'Clinging On', 'Corkscrew H', 'Water Slide', 'Continue', 'Continue Up',
                                  'Super Transform']},
 ('Sonic1', 'tails'): {'all': ['Stopped', 'Waiting', 'Bored!', 'Looking Up', 'Looking Down', 'Walking', 'Running',
                               'Skidding', 'Super Peel Out', 'Spin Dash', 'Jumping', 'Bouncing', 'Hurt', 'Dying',
                               'Drowning', 'Fan Rotate', 'Breathing', 'Pushing', 'Flailing 1', 'Flailing 2',
                               'Sliding', 'Hanging', 'Dropping', 'Clinging On', 'Flying', 'Flying Tired', 'Swimming',
                               'Swimming Tired', 'Launcher', 'Gliding Drop', 'Gliding Stop', 'Climbing',
                               'Ledge Pull Up', 'Corkscrew H', 'Corkscrew V', 'Water Slide', 'Continue',
                               'Continue Up', 'Super Transform', 'Fly Lift Down', 'Fly Lift Up', 'Fly Lift Tired',
                               'Swim Lift'],
                       'filled': ['Stopped', 'Waiting', 'Looking Up', 'Looking Down', 'Walking', 'Running',
                                  'Skidding', 'Super Peel Out', 'Spin Dash', 'Jumping', 'Bouncing', 'Hurt', 'Dying',
                                  'Drowning', 'Fan Rotate', 'Breathing', 'Pushing', 'Flailing 1', 'Flailing 2',
                                  'Clinging On', 'Flying', 'Flying Tired', 'Swimming', 'Swimming Tired',
                                  'Water Slide', 'Continue', 'Continue Up', 'Super Transform', 'Fly Lift Down',
                                  'Fly Lift Up', 'Fly Lift Tired', 'Swim Lift']},
 ('Sonic2', 'knuckles'): {'all': ['Stopped', 'Waiting', 'Bored!', 'Looking Up', 'Looking Down', 'Walking', 'Running',
                                  'Skidding', 'Super Peel Out', 'Spin Dash', 'Jumping', 'Bouncing', 'Hurt', 'Dying',
                                  'Drowning', 'Fan Rotate', 'Breathing', 'Pushing', 'Flailing 1', 'Flailing 2',
                                  'Sliding', 'Hanging', 'Grabbing', 'Clinging On', 'Flying', 'Flying Tired',
                                  'Swimming', 'Swimming Tired', 'Gliding', 'Gliding Drop', 'Gliding Stop', 'Climbing',
                                  'Ledge Pull Up', 'Twirl H', 'Twirl V', 'Water Slide', 'Continue', 'Continue Up',
                                  'Super Transform'],
                          'filled': ['Stopped', 'Waiting', 'Bored!', 'Looking Up', 'Looking Down', 'Walking',
                                     'Running', 'Skidding', 'Spin Dash', 'Jumping', 'Bouncing', 'Hurt', 'Dying',
                                     'Drowning', 'Fan Rotate', 'Breathing', 'Pushing', 'Flailing 1', 'Flailing 2',
                                     'Hanging', 'Grabbing', 'Clinging On', 'Gliding', 'Gliding Drop', 'Gliding Stop',
                                     'Climbing', 'Ledge Pull Up', 'Twirl H', 'Water Slide', 'Continue', 'Continue Up',
                                     'Super Transform']},
 ('Sonic2', 'sonic'): {'all': ['Stopped', 'Waiting', 'Bored!', 'Looking Up', 'Looking Down', 'Walking', 'Running',
                               'Skidding', 'Super Peel Out', 'Spin Dash', 'Jumping', 'Bouncing', 'Hurt', 'Dying',
                               'Drowning', 'Fan Rotate', 'Breathing', 'Pushing', 'Flailing 1', 'Flailing 2',
                               'Flailing 3', 'Hanging', 'Grabbed', 'Clinging On', 'Flying', 'Flying Tired',
                               'Swimming', 'Swimming Tired', 'Launcher', 'Gliding Drop', 'Gliding Stop', 'Climbing',
                               'Ledge Pull Up', 'Twirl H', 'Twirl V', 'Water Slide', 'Continue', 'Continue Up',
                               'Super Transform'],
                       'filled': ['Stopped', 'Waiting', 'Bored!', 'Looking Up', 'Looking Down', 'Walking', 'Running',
                                  'Skidding', 'Super Peel Out', 'Spin Dash', 'Jumping', 'Bouncing', 'Hurt', 'Dying',
                                  'Drowning', 'Fan Rotate', 'Breathing', 'Pushing', 'Flailing 1', 'Flailing 2',
                                  'Flailing 3', 'Hanging', 'Grabbed', 'Clinging On', 'Twirl H', 'Water Slide',
                                  'Continue', 'Continue Up', 'Super Transform']},
 ('Sonic2', 'tails'): {'all': ['Stopped', 'Waiting', 'Bored!', 'Looking Up', 'Looking Down', 'Walking', 'Running',
                               'Skidding', 'Super Peel Out', 'Spin Dash', 'Jumping', 'Bouncing', 'Hurt', 'Dying',
                               'Drowning', 'Fan Rotate', 'Breathing', 'Pushing', 'Flailing 1', 'Flailing 2',
                               'Sliding', 'Hanging', 'Grabbed', 'Clinging On', 'Flying', 'Flying Tired', 'Swimming',
                               'Swimming Tired', 'Launcher', 'Gliding Drop', 'Gliding Stop', 'Climbing',
                               'Ledge Pull Up', 'Twirl H', 'Twirl V', 'Water Slide', 'Continue', 'Continue Up',
                               'Super Transform', 'Fly Lift Down', 'Fly Lift Up', 'Fly Lift Tired', 'Swim Lift'],
                       'filled': ['Stopped', 'Waiting', 'Bored!', 'Looking Up', 'Looking Down', 'Walking', 'Running',
                                  'Skidding', 'Super Peel Out', 'Spin Dash', 'Jumping', 'Bouncing', 'Hurt', 'Dying',
                                  'Drowning', 'Fan Rotate', 'Breathing', 'Pushing', 'Flailing 1', 'Flailing 2',
                                  'Hanging', 'Grabbed', 'Clinging On', 'Flying', 'Flying Tired', 'Swimming',
                                  'Swimming Tired', 'Twirl H', 'Water Slide', 'Continue', 'Continue Up',
                                  'Super Transform', 'Fly Lift Down', 'Fly Lift Up', 'Fly Lift Tired', 'Swim Lift']}}
