// GENERATED by tools/gen_mania_psycho.py from the Sonic Mania decompilation's headers: do not edit.
// The badniks Silver's Psychokinesis can catch in Mania, and the offsets of the Animators their Draw shows at their own
// position, in draw order (alpha: a bit per part drawn with INK_ALPHA). Animator size 32, Entity size 96.
#ifndef MANIA_PSYCHO_TABLE_H
#define MANIA_PSYCHO_TABLE_H

#define PSYCHO_PARTS_MAX     (3)
#define PSYCHO_ANIMATOR_SIZE (32)

typedef struct {
    const char *name;
    uint8 count;
    uint16 offset[PSYCHO_PARTS_MAX];
    uint8 alpha;
} PsychoClass;

static const PsychoClass PSYCHO_CLASSES[] = {
    { "Aquis", 2, { 128, 160, 0 }, 0x0 }, // mainAnimator, wingAnimator
    { "BallHog", 1, { 120, 0, 0 }, 0x0 }, // animator
    { "Batbot", 1, { 168, 0, 0 }, 0x0 }, // bodyAnimator
    { "Batbrain", 1, { 128, 0, 0 }, 0x0 }, // animator
    { "Blaster", 1, { 128, 0, 0 }, 0x0 }, // animator
    { "Blastoid", 1, { 112, 0, 0 }, 0x0 }, // animator
    { "Bloominator", 1, { 112, 0, 0 }, 0x0 }, // animator
    { "Bubbler", 1, { 120, 0, 0 }, 0x0 }, // bodyHitbox
    { "Buggernaut", 2, { 136, 168, 0 }, 0x2 }, // bodyAnimator, ~wingAnimator
    { "Bumpalo", 2, { 128, 160, 0 }, 0x0 }, // badnikAnimator, huffAnimator
    { "BuzzBomber", 3, { 136, 168, 200 }, 0x2 }, // animator, ~wingAnimator, thrustAnimator
    { "Cactula", 3, { 152, 184, 120 }, 0x0 }, // bodyBottomAnimator, propellerAnimator, bodyTopAnimator
    { "Canista", 3, { 184, 216, 248 }, 0x0 }, // mainAnimator, tapeAnimator, cannonAnimator
    { "Chopper", 1, { 128, 0, 0 }, 0x0 }, // animator
    { "Clucker", 1, { 120, 0, 0 }, 0x0 }, // animator
    { "Crabmeat", 1, { 128, 0, 0 }, 0x0 }, // animator
    { "Dango", 1, { 128, 0, 0 }, 0x0 }, // animator
    { "FlasherMKII", 1, { 128, 0, 0 }, 0x0 }, // animator
    { "HotaruMKII", 1, { 208, 0, 0 }, 0x0 }, // mainAnimator
    { "IceBomba", 2, { 128, 160, 0 }, 0x2 }, // bodyAnimator, ~wingAnimator
    { "Jawz", 1, { 112, 0, 0 }, 0x0 }, // animator
    { "JuggleSaw", 1, { 200, 0, 0 }, 0x0 }, // animator
    { "Kanabun", 1, { 128, 0, 0 }, 0x0 }, // animator
    { "MechaBu", 2, { 136, 168, 0 }, 0x0 }, // badnikAnimator, hornAnimator
    { "MicDrop", 1, { 104, 0, 0 }, 0x0 }, // bodyAnimator
    { "Motobug", 1, { 128, 0, 0 }, 0x0 }, // animator
    { "Newtron", 1, { 120, 0, 0 }, 0x0 }, // animator
    { "Octus", 1, { 128, 0, 0 }, 0x0 }, // animator
    { "Pointdexter", 1, { 120, 0, 0 }, 0x0 }, // animator
    { "Redz", 1, { 120, 0, 0 }, 0x0 }, // animator
    { "Rhinobot", 1, { 152, 0, 0 }, 0x0 }, // bodyAnimator
    { "RollerMKII", 1, { 128, 0, 0 }, 0x0 }, // animator
    { "Shutterbug", 1, { 168, 0, 0 }, 0x0 }, // animator
    { "Spiny", 1, { 104, 0, 0 }, 0x0 }, // animator
    { "Splats", 1, { 144, 0, 0 }, 0x0 }, // mainAnimator
    { "Stegway", 2, { 128, 160, 0 }, 0x0 }, // mainAnimator, wheelAnimator
    { "Sweep", 1, { 144, 0, 0 }, 0x0 }, // animator
    { "Technosqueek", 1, { 144, 0, 0 }, 0x0 }, // animator
    { "TurboSpiker", 2, { 136, 168, 0 }, 0x0 }, // shellAnimator, animator
    { "TurboTurtle", 1, { 120, 0, 0 }, 0x0 }, // animator
    { "Vultron", 1, { 136, 0, 0 }, 0x0 }, // bodyAnimator
    { "WallCrawl", 1, { 136, 0, 0 }, 0x0 }, // animator
    { "Wisp", 2, { 128, 160, 0 }, 0x2 }, // bodyAnimator, ~wingAnimator
    { "Woodrow", 1, { 144, 0, 0 }, 0x0 }, // animator
};
#define PSYCHO_CLASS_COUNT (sizeof(PSYCHO_CLASSES) / sizeof(PSYCHO_CLASSES[0]))

#endif // MANIA_PSYCHO_TABLE_H
